title: Jamstatic
baseURL: https://jamstatic.fr
DefaultContentLanguage: fr
languageCode: fr-fr
disablePathToLower: true
enableRobotsTXT: true
metaDataFormat: yaml
permalinks:
  post: /:year/:month/:day/:filename/
footnoteReturnLinkContents: "↩"
googleAnalytics: UA-75833986-1
disqusShortname: jekyllfr

blackfriday:
  angledQuotes: true
  smartypantsQuotesNBSP: true

mediaTypes:
  "text/netlify":
    suffix: ""
    delimiter: ""

outputs:
  home:
    - html
    - rss
    - jsonfeed
    - HEADERS
    - algolia
  page:
    - html
  section:
    - rss

outputFormats:
  algolia:
    baseName: "algolia"
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true
  rss:
    baseName: "feed"
  jsonfeed:
    mediaType: "application/json"
    baseName: "feed"
    isPlainText: true
  HEADERS:
    mediaType: "text/netlify"
    baseName: "_headers"
    isPlainText: true
    notAlternative: true

params:
  title: Jamstastic
  description: Sites statiques et architectures découplées
  email: contact@jamstatic.fr
  author:
      name: Frank Taillandier
      url: https://frank.taillandier.me
      avatar: https://github.com/DirtyF.png
      GitHub: DirtyF
  social:
    twitter: jamstatic_fr
    GitHub: jamstatic
  ghrepo: https://github.com/jamstatic/jamstatic-fr/
  branch: master
  images:
    - "assets/images/twitter-card.jpg"
  algolia:
    vars:
      - title
      - summary
      - date
      - publishdate
      - expirydate
      - permalink
      - relpermalink
    params:
      - categories
    appId: TLI4UDRZDR
    indexName: jamstatic
    searchOnlyApiKey: 5af8d385eec1e00ac16d0963c630b6ac

related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
    - name: "categories"
      weight: 80
    - name: "tags"
      weight: 80
    - name: "keywords"
      weight: 80
    - name : "date"
      weight: 10
      pattern: "2006"
