title: Jamstatic
baseURL: https://jamstatic.fr
DefaultContentLanguage: fr
languageCode: fr-fr
disablePathToLower: true
enableRobotsTXT: true
metaDataFormat: yaml
permalinks:
  post: /:year/:month/:day/:filename/
footnoteReturnLinkContents: "↩"
googleAnalytics: UA-75833986-1
disqusShortname: jekyllfr


mediaTypes:
  "text/netlify":
    suffix: ""
    delimiter: ""

outputs:
  home:
    - html
    - rss
    - jsonfeed
    - HEADERS
  page:
    - html
  section:
    - rss

outputFormats:
  rss:
    baseName: "feed"
  jsonfeed:
    mediaType: "application/json"
    baseName: "feed"
    isPlainText: true
  HEADERS:
    mediaType: "text/netlify"
    baseName: "_headers"
    isPlainText: true
    notAlternative: true

params:
  title: Jamstastic
  description: Sites statiques et architectures décentralisées
  email: contact@jamstatic.fr
  author:
      name: Frank Taillandier
      url: https://frank.taillandier.me
      avatar: https://github.com/DirtyF.png
      GitHub: DirtyF
  social:
    twitter: jamstatic_fr
    GitHub: jamstatic
  ghrepo: https://github.com/jamstatic/jamstatic-fr/
  branch: master
  images:
    - "assets/images/jamstatic-card.png"

related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
    - name: "categories"
      weight: 80
    - name: "tags"
      weight: 80
    - name: "keywords"
      weight: 80
    - name : "date"
      weight: 10
      pattern: "2006"
