title: Jamstatic
baseURL: https://jamstatic.fr
DefaultContentLanguage: fr
languageCode: fr-fr
disablePathToLower: true
enableRobotsTXT: true
metaDataFormat: yaml
permalinks:
  post: /:year/:month/:day/:filename/
footnoteReturnLinkContents: "↩"
googleAnalytics: UA-75833986-1
disqusShortname: jekyllfr


mediaTypes:
  "text/netlify":
    suffix: ""
    delimiter: ""

outputs:
  home:
    - html
    - rss
    - jsonfeed
    - HEADERS
  page:
    - html
  section:
    - rss

outputFormats:
  rss:
    baseName: "feed"
  jsonfeed:
    mediaType: "application/json"
    baseName: "feed"
    isPlainText: true
  HEADERS:
    mediaType: "text/netlify"
    baseName: "_headers"
    isPlainText: true
    notAlternative: true

params:
  description: L'actualité autour des générateurs de site statique et de la JAMStack
  email: contact@jamstatic.fr
  author:
      name: Frank Taillandier
      url: https://frank.taillandier.me
      avatar: https://github.com/DirtyF.png
      GitHub: DirtyF
  social:
    twitter: jamstatic_fr
    GitHub: jamstatic
  ghrepo: https://github.com/jamstatic/jamstatic-fr/
  branch: master
