[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.55.5"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL -D -E -F"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL -D -E -F"
