backend:
  name: github
  repo: jamstatic/jamstatic-fr
  branch: master

publish_mode: editorial_workflow

media_folder: "static/assets/images"
public_folder: "/assets/images/"

collections:
  - name: "Article"
    label: "Article"
    folder: "content/post"
    create: true
    format: yaml-frontmatter
    extension: md
    fields: # The fields for each document, usually in front matter
      - label: "Titre"
        name: "title"
        widget: "string"

      - label: "Description"
        name: "description"
        widget: "string"

      - label: "Catégories"
        name: "categories"
        required: false
        widget: "list"

      - label: "Source"
        name: "source"
        required: false
        widget: "object"
        fields:
          - {label: "Auteur", name: author, widget: string}
          - {label: "Titre", name: title, widget: string}
          - {label: "URL", name: url, widget: string}

      - label: "Twitter Card"
        name: "images"
        required: false
        widget: "list"
        field:
          - {label: Image, name: image, widget: image}

      - label: "Texte"
        name: "body"
        widget: "markdown"
