---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: ''
sections:
- type: directory
  path: content/a-propos
  label: A propos
  create: none
  match: "**/*"
  hidden: true
- type: directory
  path: content/post
  label: Articles
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: content
  label: Pages
  create: none
  match: "*"
  hidden: true
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: '0.48'
