---
new_page_extension: md
auto_deploy: false
sections:
- path: content/a-propos
  label: A propos
  create: none
  hidden: true
- path: content/post
  label: Articles
  create: all
  default_front_matter_template: post
- path: content
  label: Pages
  create: none
  hidden: true
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path:
file_template: ":filename:"
version: 0.42.1
